/* Do not edit. File generated by rastro_generate. */

#include <rastro.h>

void rst_event_iiss_f_( int16_t *type, int32_t *i0, int32_t *i1, char *s0, char *s1)
{
	rst_event_iiss(  (u_int16_t)*type, (u_int32_t)*i0, (u_int32_t)*i1, s0, s1);
}
void rst_event_ii_f_( int16_t *type, int32_t *i0, int32_t *i1)
{
	rst_event_ii(  (u_int16_t)*type, (u_int32_t)*i0, (u_int32_t)*i1);
}
void rst_event_iiiss_f_( int16_t *type, int32_t *i0, int32_t *i1, int32_t *i2, char *s0, char *s1)
{
	rst_event_iiiss(  (u_int16_t)*type, (u_int32_t)*i0, (u_int32_t)*i1, (u_int32_t)*i2, s0, s1);
}
void rst_init_f_(int64_t * id1, int64_t * id2) { 
 rst_init((u_int64_t)*id1, (u_int64_t)*id2);
}

void rst_finalize_f_ () {  rst_finalize(); }
