/* Do not edit. File generated by rastro_generate. */

#include "rastro_functs.h"

void rst_event_l_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0)
{
	rst_startevent(ptr, type<<18|0x24000);
	RST_PUT(ptr, u_int64_t, l0);
	rst_endevent(ptr);
}

void rst_event_ll_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int64_t l1)
{
	rst_startevent(ptr, type<<18|0x24400);
	RST_PUT(ptr, u_int64_t, l0);
	RST_PUT(ptr, u_int64_t, l1);
	rst_endevent(ptr);
}

void rst_event_s_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0)
{
	rst_startevent(ptr, type<<18|0x21000);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

void rst_event_si_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, u_int32_t i0)
{
	rst_startevent(ptr, type<<18|0x27100);
	RST_PUT(ptr, u_int32_t, i0);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

void rst_event_sll_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, u_int64_t l0, u_int64_t l1)
{
	rst_startevent(ptr, type<<18|0x24410);
	RST_PUT(ptr, u_int64_t, l0);
	RST_PUT(ptr, u_int64_t, l1);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

void rst_event_ss_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, char *s1)
{
	rst_startevent(ptr, type<<18|0x21100);
	RST_PUT_STR(ptr, s0);
	RST_PUT_STR(ptr, s1);
	rst_endevent(ptr);
}

