/* Do not edit. File generated by rastro_generate. */

#ifndef _RASTRO_rastro_functs_H_
#define _RASTRO_rastro_functs_H_

#include "rastro.h"
#include "rastro_private.h"

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_l_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0);
#define rst_event_l(type, l0) rst_event_l_ptr(RST_PTR, type, l0)
#else
#define rst_event_l(type, l0) 
#endif

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_ll_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int64_t l1);
#define rst_event_ll(type, l0, l1) rst_event_ll_ptr(RST_PTR, type, l0, l1)
#else
#define rst_event_ll(type, l0, l1) 
#endif

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_s_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0);
#define rst_event_s(type, s0) rst_event_s_ptr(RST_PTR, type, s0)
#else
#define rst_event_s(type, s0) 
#endif

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_si_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, u_int32_t i0);
#define rst_event_si(type, s0, i0) rst_event_si_ptr(RST_PTR, type, s0, i0)
#else
#define rst_event_si(type, s0, i0) 
#endif

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_sll_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, u_int64_t l0, u_int64_t l1);
#define rst_event_sll(type, s0, l0, l1) rst_event_sll_ptr(RST_PTR, type, s0, l0, l1)
#else
#define rst_event_sll(type, s0, l0, l1) 
#endif

#ifndef RASTRO_DISABLE_EVENTS
void rst_event_ss_ptr(rst_buffer_t *ptr, u_int16_t type, char *s0, char *s1);
#define rst_event_ss(type, s0, s1) rst_event_ss_ptr(RST_PTR, type, s0, s1)
#else
#define rst_event_ss(type, s0, s1) 
#endif


#endif
